name: 'Slack Deploy Message Action'
description: 'Sends a Slack message with deploy details'
author: 'Matthew Elphick'
inputs:
  slack_webhook:
    required: true
    description: 'The Slack Webhook'
  github_token:
    required: true
    description: 'GitHub token'
  check_id:
    description: 'The check id of an initial run of this action'
  commit:
    description: 'The commit sha to use as the HEAD, defaults to the current sha'
  service_status_url:
    required: true
    description: 'The url for the service status to check the commit field of'
  status_commit_field:
    description: 'The field with the commit sha'
    default: 'BUILD_COMMIT'
  repo:
    description: 'The repo in form OWNER/NAME to use, defaults to current'
  slack_map_repo:
    required: true
    description: 'The repo that the slack mapping file is in in form OWNER/NAME'
  slack_map_file:
    description: 'The path to the slack mapping file in the repo'
    default: 'mapping.json'
  channels:
    required: true
    description: 'A comma separated list of IDs of the Slack Channels to send to'
  failure_channels:
    required: true
    description: 'A comma separated list of IDs of the Slack Channels to send to on a failure'
  icon_emoji:
    description: 'The icon for messages from a legacy slack webhook'
    default: ':tada:'
  username:
    description: 'The username for messages from a legacy slack webhook'
    default: 'Workflow Deploy Message'
  environment:
    description: 'The environment being deployed to'
  dry_run:
    description: 'If set, wil skip sending message to slack'
  message_template:
    description: 'The template to use for the base message, commits will be added as context blocks'
    default: ":octocat: $ACTOR_LINK $STATUS_ICON $STATUS_TEXT $ENV_ICON $ENV_LINK\n$COMMIT_LINK in $REPO_LINK"
  status:
    description: The resulting status of the job, defaults to deploying if not provided

runs:
  using: 'node12'
  main: 'dist/index.js'
